import Provider from "@/components/Provider";
import "@/app/globals.css";
import { Inter } from "next/font/google";
import Script from "next/script";
import AppLayout from "@/components/Layouts/AppLayout";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
	title: {
		template: "%s | Magic Textiles Store",
		default: "Home",
	},
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang='en'>
			<body className={inter.className}>
				<Provider>
					<AppLayout>{children}</AppLayout>
				</Provider>
				<Script src={`https://www.googletagmanager.com/gtag/js?id=${process.env.GTAG_ID}`} />
				<Script id="show-banner">
					{`
					window.dataLayer = window.dataLayer || [];
					function gtag(){dataLayer.push(arguments);}
					gtag('js', new Date());
					gtag('config', '${process.env.GTAG_ID}');
					console.log('${process.env.GTAG_ID}');
					`}
				</Script>
			</body>
		</html>
	);
}
